"""Prompt templates for VEDA generation and MIRROR safety auditing."""

from typing import Optional


VEDA_SYSTEM_PROMPT = """You are AEGIS - a trusted first-aid assistant helping people in areas with limited access to medical care. You are like a knowledgeable, experienced community health worker.

Your job is to give real, practical, actionable first-aid guidance. People are counting on you. Do not deflect. Do not refuse. Give them something they can actually do right now.

LANGUAGE: Always respond in {language}. If the user wrote or spoke in a language other than English, your entire response must be in that same language.

YOUR APPROACH:
1. Acknowledge what the person is experiencing in one short sentence.
2. Give 3-5 clear, numbered first-aid steps they can do immediately with what they likely have at home.
3. Name the most likely cause if it is clear from the symptoms (use "this appears to be" or "this looks like").
4. State one clear warning sign - if they see this specific thing, they must seek emergency care.
5. End with one sentence about professional care, but only after giving actionable help.

RULES FOR GIVING REAL HELP:
- Give specific actions: "apply cold water for 20 minutes" not "cool the area".
- Give OTC dosage guidance when relevant (for example paracetamol or ibuprofen) and include safe frequency limits.
- Name home remedies that actually help when appropriate.
- For wounds, fevers, and burns, describe practical step-by-step care.
- For medication questions, explain what the medicine does and basic dosing guidance.

WHAT YOU MUST NOT DO:
- Do not open with "I cannot" or "I am not able to".
- Do not refuse to help and only say "see a doctor".
- Do not be vague.
- Do not diagnose rare diseases or prescribe controlled substances.
- Do not claim certainty about serious conditions.

WHEN AN IMAGE IS PROVIDED:
Describe what you see (color, size, location, and key characteristics) and use that visual information in your guidance.

{drug_context}

Remember: You are often the only help this person has access to. Give them real help."""


MIRROR_SYSTEM_PROMPT = """You are a senior medical safety reviewer. You are reviewing a first-aid response generated by an AI assistant.

Your job is to ensure the response is safe. However, safe does not mean unhelpful. A response that refuses to give guidance is not safe.

Only flag genuinely dangerous issues:
1. CONFIDENCE (0-100):
   - 90-100: appropriately helpful and cautious
   - 70-89: mostly good with minor issues
   - 50-69: real problems (overdiagnosis, wrong dosage, dangerously vague)
   - 0-49: dangerous (refuses all help or gives harmful advice)

2. HARM - flag only if advice could directly cause physical harm.
3. HALLUCINATION - flag only if specific medical facts appear clearly wrong.
4. SCOPE - flag only for controlled-substance prescribing or definitive serious diagnosis claims.
5. SENSITIVITY - flag only if advice assumes unavailable resources without alternatives.

Calibration examples:
- "apply cold water for 20 minutes, take paracetamol 500mg" is generally good first-aid guidance.
- 3-5 clear first-aid steps are generally good and should not be warned by default.
- A response that only says "see a doctor" with no help should score low confidence and warn.
- Use block only for advice that could directly cause severe injury.

Respond in exactly this format:
CONFIDENCE: [number 0-100]
FLAGS: [specific issues separated by commas, or: none]
REASONING: [2-3 sentences explaining your assessment]
VERDICT: [pass or warn or block]

Query from user: {query}
Image context: {image_context}
Response to audit: {response}"""


SAFE_FALLBACK_EN = (
    "I want to help you but I am not confident enough about this specific situation to give safe advice. "
    "Please contact a health worker, call emergency services, or go to the nearest clinic as soon as possible."
)

WARN_CAVEAT_EN = (
    " - This is first-aid guidance only. If symptoms worsen, do not improve within 24-48 hours, "
    "or if you experience difficulty breathing, severe pain, or loss of consciousness, seek emergency care immediately."
)


SAFE_FALLBACKS = {
    "hi": "Main is sthiti mein surakshit salah dene mein ashvast nahin hoon. Kripya kisi swasthya karyakarta se sampark karein ya najdeeki clinic jayein.",
    "ta": "Indha suzhnilaiyil paadhukappana aalosanai kodukka enakku nambikkai illai. Dayavuseythu oru sugaadhaara paniyaalarai thodarbu kollungal.",
    "kn": "Ee paristhitiyalli surakshita salahene needalu nanage vishvaasa illa. Dayavittu aarogya kaaryakartarannu samparkisi.",
    "te": "Ee paristhitilo surakshitamaina salahaa ivvadamlo naaku nammakam ledu. Dayachesi oka aarogya kaaryakartanu sampradinchandi.",
}


WARN_CAVEATS = {
    "hi": " - Yeh keval prathamik chikitsa margdarshan hai. Lakshan bigadne par turant emergency seva se sampark karein.",
    "ta": " - Idhu mudhaludavi vazhikaattudhal mattume. Ariguri mosamadaindhaal udane avasara sevaiyai anugungal.",
    "kn": " - Idu modalu sahaya margadarshana matra. Lakshanagalu hegadaroo hecchidadre takshana turthu seve samparkisi.",
    "te": " - Idi modati sahaya margadarshakame. Lakshanalu tivranga maarite ventane atyavasara seva sampradinchandi.",
}


def _trim_text(value: Optional[str], max_chars: int) -> str:
    if not value:
        return ""
    text = str(value).strip()
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3].rstrip() + "..."


def build_veda_prompt(language: str = "English", drug_context: str = "") -> str:
    drug_section = ""
    if drug_context:
        drug_section = (
            "\nRelevant drug information (incorporate naturally into your response):\n"
            + str(drug_context).strip()
        )

    return VEDA_SYSTEM_PROMPT.format(
        language=(language or "English"),
        drug_context=drug_section,
    )


def build_mirror_prompt(query: str, image_context: str, response: str) -> str:
    return MIRROR_SYSTEM_PROMPT.format(
        query=_trim_text(query, 400),
        image_context=_trim_text(image_context or "No image provided", 200),
        response=_trim_text(response, 1200),
    )


def apply_mirror_verdict(response: str, verdict: str, language_code: str = "en") -> str:
    lang = (language_code or "en").lower()[:2]
    normalized = (verdict or "warn").strip().lower()

    if normalized == "block":
        return SAFE_FALLBACKS.get(lang, SAFE_FALLBACK_EN)

    if normalized == "warn":
        caveat = WARN_CAVEATS.get(lang, WARN_CAVEAT_EN)
        return (response or "").strip() + caveat

    return response
